finish mobile version project
DamenaM/Portofolio pull request #3
Opened 2022-11-01 11:20 UTC by DamenaM

# Request of  PR I  finish the mobile version project

- [ ] create Works section
- [ ] check  linter error
- [ ] c=Create About myself section
- [ ]  adding cards template using Flexbox to lay out 
- [ ] use CSS Grid and Flexbox

2022-11-01 12:48 UTC, Olamarx requested changes
Hi @DamenaM, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/hXz6GN0ZilLwhgLo49/giphy.gif"/>

## Highlights
- All linters passed ✔️ 
- Good commit messages ✅ 

## Required Changes ♻️
_Check the comments under the review._

- [ ] Please consider applying the comment about button to all the buttons.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-01 12:48 UTC, Olamarx commented on style.css
> +}
- [ ] For proper organizing of the content in this tag, could you consider styling it with grid as display property? You can read about the usefulness [here](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns)

2022-11-01 12:48 UTC, Olamarx commented on index.html
> +    <a class="card1" href="#"><img src="./image/Snapshoot Portfolio1 (1).png" alt=""></a>
- [ ] Kindly consider using this picture through CSS as a background image as decorations are always backgrounded images, not img tags.

2022-11-01 12:48 UTC, Olamarx commented on index.html
> +   </div>
- [ ] Kindly consider using ul tag and each takes li tag to satisfy semantic purpose.

2022-11-01 12:48 UTC, Olamarx commented on index.html
> +    <button class="buttonProject"  type="button" class="resume-btn">See Project</button>
- [ ] Kindly consider the color as used on the figma
### Figma
![image](https://user-images.githubusercontent.com/86200356/199233248-4de7845f-bf84-421b-ab08-7b2b905fd3ea.png)

### Your Design
![image](https://user-images.githubusercontent.com/86200356/199233312-473a4136-79fc-4e41-a229-a20332ef60e9.png)

2022-11-01 12:48 UTC, Olamarx commented on index.html
> +     </ul>
- [ ] This appears not to be on the Figma design. I would recommend sticking to the Figma template.

### Your Design
![image](https://user-images.githubusercontent.com/86200356/199234199-4580eecd-eada-4db9-8817-aee13d3ac8d4.png)

### Figma Design
![image](https://user-images.githubusercontent.com/86200356/199234386-f099390c-ce2f-4b0e-97b3-f95705c38a24.png)

2022-11-01 12:48 UTC, Olamarx commented on index.html
> +    <h4 class="connectmywork"> LET’S CONNECT</p>
- [ ] This confuses me. It is opening the tag with h4 and classes it with p tag 😒.

2022-11-02 09:37 UTC, DamenaM commented
> based on PR comment

- [ ] border-radius
- [ ] I have changed my background image to CSS 
- [ ] I have changed div tag ul tag 
- [ ] I Have changed button color to figma design

2022-11-02 10:02 UTC, sajid-munawar requested changes
Hi @DamenaM , 

_Great job so far 👏 💯 👍. You've done well implementing some of the requested changes. However, there are still some which aren't addressed yet. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 
  - Addressed some of the issues raised from the previous review. 💯 

## Required Changes ♻️
  - [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
  
  - N/A 

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-11-02 10:02 UTC, sajid-munawar commented on index.html
> +        </ul>
- [Optional] Iam sorry that it was not pointed out by the previous reviewer, I strongly suggest you to change the languages from image to text as it is not an image. they are texts.
![img](https://user-images.githubusercontent.com/66992901/199460867-3a78b762-5e56-47e9-97a0-47be2b7dd7c3.PNG)

2022-11-02 13:34 UTC, merged